spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keyckoak-prod-production-551c.up.railway.app/realms/gestionrh
  application:
    name: gestionRh

  datasource:
    url: jdbc:postgresql://switchback.proxy.rlwy.net:26374/railway
    username: postgres
    password: LqTiOhdbLKcRMBIKXgecOKeNwfmXGdHl
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  # sql:
  #  init:
  #    mode: always
  #    data-locations: classpath:import.sql

# Configuration Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
    title: Gestion RH API
    description: Documentation de l'API pour la gestion RH
  swagger-ui:
    path: /swagger-ui.html

keycloak:
  realm: gestionrh
  auth-server-url: https://keyckoak-prod-production-551c.up.railway.app
  resource: gestionRhback
  credentials:
    secret: 3QB7anfZfRsGlzPpB5CR0PX8pVHisLdG
  client-id: gestionRhback
